### ISSUE TITLE
Design Initial User Console

### ISSUE THREAD

**Issue by SebastinSanty** [OSDLabs/swd#11]
TSIA

**Comment by prampey** [comment]
This is the admin console meant for SWD staff right?

**Comment by SebastinSanty** [comment]
This is meant for everyone who accesses data. Admin is just another user with more authorization than a student. The components, can fiddled around based upon a state variable, if need arises.

**Comment by prampey** [comment]
So how will a student use it?

**Comment by prampey** [comment]
Console looks great btw
