### ISSUE TITLE
Remove Header Package

### ISSUE THREAD

**Issue by SebastinSanty** [OSDLabs/swd#29]
Header isn't needed, as the bdome image can be put directly into the home page. Also it is a clutter if it is there on every page, as @mukkachaitanya suggested.

**Comment by prampey** [comment]
Headers and footers are a convention for every webpage, plus the Header component consists of the Navbar component.
A simpler way would be to simply offload the 'bdome' cover into the Home component.

**Comment by SebastinSanty** [comment]
Yes, offload 'bdome' cover to the Home component. Header is just 'bdome' cover + navbar, hence if 'bdome'  cover is removed, it makes no sense to have Header any longer. We can just call Navigation Component directly into the Layout.

**Comment by prampey** [comment]
For the sake of future requirements, I think it's best to leave 'Header' as is. For eg, later on, when we include a Sidebar or Drawer component, it will be definitely grouped under 'Header', as a requirement for every page. Therefore, 'Header' serves as a really good semantic as well.

**Comment by SebastinSanty** [comment]
I have included the Drawer directly into the Layout [here](https://github.com/OSDLabs/swd/pull/27/files#diff-1262ee851841cfa44ca3175c7d57b94aR49). Perhaps I should put that in the Header, yeah, that makes more sense. But while I was passing props through the layouts, I felt that an extra layer was making it a bit more complex.

**Comment by mukkachaitanya** [comment]
I agree with @prampey with this. I would recommend to leave header as is for future uses.
