### ISSUE TITLE
Right Click

### ISSUE THREAD

**Issue by sanket1001** [OSDLabs/swd#31]
There is no response when I press right click on the website, except for the borders. It does not seem to be a user-specific issue since my right click works normally on other websites and windows os.

**Comment by sanket1001** [comment]
There seems to have been a confusion with the old and new website(s).

**Comment by SebastinSanty** [comment]
@sanket1001 Hmm, yeah. This is a new website which will come up in a short time. BTW the problem you are facing is because right clicks are disabled on the old (present) swd website.
