### ISSUE TITLE
Fix errors/warnings in ESLint

### ISSUE THREAD

**Issue by sharanry** [OSDLabs/swd#32]
Should the camel-case requirement be removed considering its creating so many unnecessary warnings or should we adhere to camelcase convention?

![ss](https://user-images.githubusercontent.com/19674071/29303439-7b786316-81aa-11e7-946b-2d0c767fa646.png)

**Comment by UtkarshMe** [comment]
I think the better way forward would be to convert them to adhere to this rule, but considering the number of warnings, this is too tedious to be done.

Either write a script to do this, or keep the warnings for the mean time, cause warnings don't really cause the build to fail in Travis.

**Comment by sharanry** [comment]
the build is failing due to many unused functions.. which wont be resolved for some more time i guess

**Comment by UtkarshMe** [comment]
Not just that, though. But somebody has to fix them sometime. You can look into it if you wanna(?)

**Comment by SebastinSanty** [comment]
ESLint standard enforces CamelCase. Lets abide by that.
