### ISSUE TITLE
An efficient way of labelling issues on github

### ISSUE THREAD

**Issue by SebastinSanty** [OSDLabs/swd#9]
We can follow [scikit](https://github.com/scikit-learn/scikit-learn/issues)'s labelling scheme

**Comment by SebastinSanty** [comment]
Okay, so I have added some labels. Can you guys check and close the issue? @mukkachaitanya @prampey

**Comment by prampey** [comment]
Yeah. Looks great!

**Comment by prampey** [comment]
What does the blocker tag imply?

**Comment by SebastinSanty** [comment]
`blocker` means, if it is impacting the closing of a major (meta) issue or milestone.

**Comment by mukkachaitanya** [comment]
Looks good!

**Comment by prampey** [comment]
I'll close it then
